package bwie.com.manshopping.GreenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import bwie.com.manshopping.GreenDao.Shooping;
import bwie.com.manshopping.GreenDao.GreenDao_Count.Count_Price;

import bwie.com.manshopping.GreenDao.ShoopingDao;
import bwie.com.manshopping.GreenDao.GreenDao_Count.Count_PriceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig shoopingDaoConfig;
    private final DaoConfig count_PriceDaoConfig;

    private final ShoopingDao shoopingDao;
    private final Count_PriceDao count_PriceDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        shoopingDaoConfig = daoConfigMap.get(ShoopingDao.class).clone();
        shoopingDaoConfig.initIdentityScope(type);

        count_PriceDaoConfig = daoConfigMap.get(Count_PriceDao.class).clone();
        count_PriceDaoConfig.initIdentityScope(type);

        shoopingDao = new ShoopingDao(shoopingDaoConfig, this);
        count_PriceDao = new Count_PriceDao(count_PriceDaoConfig, this);

        registerDao(Shooping.class, shoopingDao);
        registerDao(Count_Price.class, count_PriceDao);
    }
    
    public void clear() {
        shoopingDaoConfig.clearIdentityScope();
        count_PriceDaoConfig.clearIdentityScope();
    }

    public ShoopingDao getShoopingDao() {
        return shoopingDao;
    }

    public Count_PriceDao getCount_PriceDao() {
        return count_PriceDao;
    }

}
